---
- name: unattended-upgrades | enable recommended updates
  ansible.builtin.replace:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '\/\/	\"\${distro_id}:\${distro_codename}-updates\";'
    replace: '	"${distro_id}:${distro_codename}-updates";'

- name: unattended-upgrades | enable remove unused kernels
  ansible.builtin.replace:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '\/\/Unattended-Upgrade::Remove-Unused-Kernel-Packages \"true\";'
    replace: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";'

- name: unattended-upgrades | enable remove new unused dependencies
  ansible.builtin.replace:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '\/\/Unattended-Upgrade::Remove-New-Unused-Dependencies \"true\";'
    replace: 'Unattended-Upgrade::Remove-New-Unused-Dependencies "true";'

- name: unattended-upgrades | enable remove unused dependencies
  ansible.builtin.replace:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '\/\/Unattended-Upgrade::Remove-Unused-Dependencies \"false\";'
    replace: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'