- name: post-configuration tasks
  hosts: all
  connection: ssh
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  - name: users | lock packer user
    user:
      name: "{{ packer_user }}"
      expires: 0